# Generated by Django 4.0.5 on 2022-06-27 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super_types', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuperType',
        ),
    ]
